In [1]:
import numpy as np 

def generate_patterns(n, k, m, pattern=[]):
    patterns = []  # List to store all the patterns

    if len(pattern) == n:  # Base case: Pattern is complete
        if sum(pattern) == m:  # Check if the pattern satisfies the total number of balls
            patterns.append(pattern.copy())
        return patterns
    
    for i in range(k + 1):  # Iterate over the capacities of the current box
        if sum(pattern) + i <= m:  # Check if adding i balls to the pattern is valid
            patterns += generate_patterns(n, k, m, pattern + [i])  # Recursive call to generate next box pattern

    return patterns

# Example usage
n = 3  # Number of boxes
k = 2  # Capacity of each box
m = 4  # Total number of balls

all_patterns = np.array(generate_patterns(n, k, m))
print(all_patterns)


[[0 2 2]
 [1 1 2]
 [1 2 1]
 [2 0 2]
 [2 1 1]
 [2 2 0]]


In [2]:
for i in all_patterns:
    print(i)

[0 2 2]
[1 1 2]
[1 2 1]
[2 0 2]
[2 1 1]
[2 2 0]
